### ISSUE TITLE
zsh: command not found: mediummd

### ISSUE THREAD

**Issue by hasimyerlikaya** [Piotr1215/medium-to-markdown#3]
Hi,

I'm trying to use your package but I could not run the command.
I think I need to add "mediummd" to the path but I don't know what should I add.
Can you help me with that please?

**Comment by hasimyerlikaya** [comment]
Hi,

Thank you. Now I can run the command but I hit another issue.

```
Error converting HTML to Markdown: Command failed: pandoc --from html --to gfm -o /Users/hasimyerlikaya/test/blog.md /Users/hasimyerlikaya/test/blog.html
/bin/sh: pandoc: command not found
```

**Comment by hasimyerlikaya** [comment]
I installed pandoc and now it is working.
Maybe you can mention that we should install pandoc before using this package.
This worked for me;

`brew install pandoc`

**Comment by Piotr1215** [comment]
Good idea! Added a `Prerequisites` section to the README.
